// Generated by Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import EVReflection;
@import ObjectiveC;
@import UIKit;
@import CoreGraphics;
@import Foundation;
@import AVFoundation;
@import MBProgressHUD;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

SWIFT_CLASS("_TtC15SharelinkKernel13BahamutObject")
@interface BahamutObject : EVObject
- (NSString * __nonnull)getObjectUniqueIdName;
- (NSString * __nonnull)getObjectUniqueIdValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UserLink;
@class Sharelinker;

SWIFT_CLASS("_TtC15SharelinkKernel9AULReturn")
@interface AULReturn : BahamutObject
@property (nonatomic, strong) UserLink * __null_unspecified newLink;
@property (nonatomic, strong) Sharelinker * __null_unspecified newUser;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel23ShareLinkSDKRequestBase")
@interface ShareLinkSDKRequestBase : NSObject
- (int32_t)getMaxRequestCount;
- (void)incRequest;
- (void)decRequest;
- (int32_t)getCurrentRequestCount;
@property (nonatomic, copy) NSString * __null_unspecified version;
@property (nonatomic, copy) NSString * __null_unspecified apiServerUrl;
@property (nonatomic, copy) NSString * __null_unspecified api;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * __nonnull headers;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel23AcceptAskingLinkRequest")
@interface AcceptAskingLinkRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified sharelinkerId;
@property (nonatomic, copy) NSString * __null_unspecified noteName;
@end

@class NSNumber;
@class NSDate;

SWIFT_CLASS("_TtC15SharelinkKernel7Account")
@interface Account : BahamutObject
@property (nonatomic, copy) NSString * __null_unspecified accountName;
@property (nonatomic, copy) NSString * __null_unspecified accountId;
@property (nonatomic, copy) NSString * __null_unspecified createTime;
@property (nonatomic, copy) NSString * __null_unspecified email;
@property (nonatomic, copy) NSString * __null_unspecified mobile;
@property (nonatomic, copy) NSString * __null_unspecified name;
@property (nonatomic, strong) NSNumber * __null_unspecified birthdate;
- (NSString * __nonnull)getObjectUniqueIdName;
@property (nonatomic, readonly, strong) NSDate * __null_unspecified createTimeOfDate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel21GetShareThingsRequest")
@interface GetShareThingsRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) NSDate * __null_unspecified beginTime;
@property (nonatomic, strong) NSDate * __null_unspecified endTime;
@end

@class SharelinkTheme;

SWIFT_CLASS("_TtC15SharelinkKernel23AddNewShareThingRequest")
@interface AddNewShareThingRequest : GetShareThingsRequest
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified shareType;
@property (nonatomic, copy) NSString * __null_unspecified shareContent;
@property (nonatomic, copy) NSArray<SharelinkTheme *> * __null_unspecified tags;
@property (nonatomic, copy) NSString * __null_unspecified message;
@end


SWIFT_CLASS("_TtC15SharelinkKernel16AddNewTagRequest")
@interface AddNewTagRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified tagName;
@property (nonatomic, copy) NSString * __null_unspecified tagColor;
@property (nonatomic, copy) NSString * __null_unspecified data;
@property (nonatomic, copy) NSString * __null_unspecified isFocus;
@property (nonatomic, copy) NSString * __null_unspecified isShowToLinkers;
@property (nonatomic, copy) NSString * __null_unspecified type;
@end


SWIFT_CLASS("_TtC15SharelinkKernel18AddUserLinkRequest")
@interface AddUserLinkRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified otherUserId;
@property (nonatomic, copy) NSString * __null_unspecified message;
@end


SWIFT_CLASS("_TtC15SharelinkKernel16VotesRequestBase")
@interface VotesRequestBase : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified shareId;
@end


SWIFT_CLASS("_TtC15SharelinkKernel14AddVoteRequest")
@interface AddVoteRequest : VotesRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@interface BahamutObject (SWIFT_EXTENSION(SharelinkKernel))
@end


SWIFT_CLASS("_TtC15SharelinkKernel28ChangeAccountPasswordRequest")
@interface ChangeAccountPasswordRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified oldPassword;
@property (nonatomic, copy) NSString * __null_unspecified newPassword;
@end


SWIFT_CLASS("_TtC15SharelinkKernel31ClearShareUpdatedMessageRequest")
@interface ClearShareUpdatedMessageRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel25DeleteLinkMessagesRequest")
@interface DeleteLinkMessagesRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel17DeleteVoteRequest")
@interface DeleteVoteRequest : VotesRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel14FileAccessInfo")
@interface FileAccessInfo : BahamutObject
- (NSString * __nonnull)getObjectUniqueIdName;
@property (nonatomic, copy) NSString * __null_unspecified fileId;
@property (nonatomic, copy) NSString * __null_unspecified server;
@property (nonatomic, copy) NSString * __null_unspecified accessKey;
@property (nonatomic, copy) NSString * __null_unspecified bucket;
@property (nonatomic, copy) NSString * __null_unspecified expireAt;
@property (nonatomic, copy) NSString * __null_unspecified serverType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface FileAccessInfo (SWIFT_EXTENSION(SharelinkKernel))
@end


SWIFT_CLASS("_TtC15SharelinkKernel18FileAccessInfoList")
@interface FileAccessInfoList : BahamutObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel26FinishNewShareThingRequest")
@interface FinishNewShareThingRequest : GetShareThingsRequest
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified shareId;
@property (nonatomic) BOOL taskSuccess;
@end


SWIFT_CLASS("_TtC15SharelinkKernel17GetAccountRequest")
@interface GetAccountRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel21GetBahamutFireRequest")
@interface GetBahamutFireRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified fileId;
@end


SWIFT_CLASS("_TtC15SharelinkKernel22GetLinkMessagesRequest")
@interface GetLinkMessagesRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel24GetLinkedUserTagsRequest")
@interface GetLinkedUserTagsRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified userId;
@end


SWIFT_CLASS("_TtC15SharelinkKernel19GetMyAllTagsRequest")
@interface GetMyAllTagsRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel21GetNewMessagesRequest")
@interface GetNewMessagesRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel22GetShareMessageRequest")
@interface GetShareMessageRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) NSDate * __null_unspecified newerThanTime;
@property (nonatomic, copy) NSString * __null_unspecified chatId;
@end


SWIFT_CLASS("_TtC15SharelinkKernel25GetShareOfShareIdsRequest")
@interface GetShareOfShareIdsRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSArray<NSString *> * __null_unspecified shareIds;
@end



SWIFT_CLASS("_TtC15SharelinkKernel29GetShareUpdatedMessageRequest")
@interface GetShareUpdatedMessageRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel22GetSharelinkersRequest")
@interface GetSharelinkersRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSArray<NSString *> * __null_unspecified userIds;
@end


SWIFT_CLASS("_TtC15SharelinkKernel19GetUserLinksRequest")
@interface GetUserLinksRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
@class NSCoder;
@class CAAnimation;

SWIFT_CLASS("_TtC15SharelinkKernel18KDCircularProgress")
@interface KDCircularProgress : UIView
@property (nonatomic) NSInteger angle;
@property (nonatomic) NSInteger startAngle;
@property (nonatomic) BOOL clockwise;
@property (nonatomic) BOOL roundedCorners;
@property (nonatomic) CGFloat gradientRotateSpeed;
@property (nonatomic) CGFloat glowAmount;
@property (nonatomic) CGFloat progressThickness;
@property (nonatomic) CGFloat trackThickness;
@property (nonatomic, strong) UIColor * __nonnull trackColor;
@property (nonatomic, copy) NSArray<UIColor *> * __null_unspecified progressColors;
@property (nonatomic, strong) UIColor * __nullable IBColor1;
@property (nonatomic, strong) UIColor * __nullable IBColor2;
@property (nonatomic, strong) UIColor * __nullable IBColor3;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (null_unspecified instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
+ (Class __nonnull)layerClass;
- (void)animateFromAngle:(NSInteger)fromAngle toAngle:(NSInteger)toAngle duration:(NSTimeInterval)duration completion:(void (^ __nullable)(BOOL))completion;
- (void)animateToAngle:(NSInteger)toAngle duration:(NSTimeInterval)duration completion:(void (^ __nullable)(BOOL))completion;
- (void)pauseAnimation;
- (void)stopAnimation;
- (BOOL)isAnimating;
- (void)animationDidStop:(CAAnimation * __nonnull)anim finished:(BOOL)flag;
- (void)didMoveToWindow;
- (void)willMoveToSuperview:(UIView * __nullable)newSuperview;
- (void)prepareForInterfaceBuilder;
@end


SWIFT_CLASS("_TtC15SharelinkKernel11LinkMessage")
@interface LinkMessage : BahamutObject
@property (nonatomic, copy) NSString * __null_unspecified id;
@property (nonatomic, copy) NSString * __null_unspecified sharelinkerId;
@property (nonatomic, copy) NSString * __null_unspecified sharelinkerNick;
@property (nonatomic, copy) NSString * __null_unspecified type;
@property (nonatomic, copy) NSString * __null_unspecified message;
@property (nonatomic, copy) NSString * __null_unspecified avatar;
@property (nonatomic, copy) NSString * __null_unspecified time;
- (NSString * __nonnull)getObjectUniqueIdName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface LinkMessage (SWIFT_EXTENSION(SharelinkKernel))
@end


@interface LinkMessage (SWIFT_EXTENSION(SharelinkKernel))
- (BOOL)isAskingLinkMessage;
- (BOOL)isAcceptAskLinkMessage;
@end

@class NSData;

SWIFT_CLASS("_TtC15SharelinkKernel7Message")
@interface Message : BahamutObject
@property (nonatomic, copy) NSString * __null_unspecified msgId;
@property (nonatomic, copy) NSString * __null_unspecified senderId;
@property (nonatomic, copy) NSString * __null_unspecified chatId;
@property (nonatomic, copy) NSString * __null_unspecified shareId;
@property (nonatomic, copy) NSString * __null_unspecified msg;
@property (nonatomic, copy) NSString * __null_unspecified time;
@property (nonatomic, copy) NSString * __null_unspecified data;
@property (nonatomic, copy) NSString * __null_unspecified msgType;
- (NSString * __nonnull)getObjectUniqueIdName;
@property (nonatomic, readonly, strong) NSData * __null_unspecified msgData;
@property (nonatomic, readonly, strong) NSDate * __null_unspecified timeOfDate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface Message (SWIFT_EXTENSION(SharelinkKernel))
@end

@class NSDateFormatter;

@interface NSDate (SWIFT_EXTENSION(SharelinkKernel))
- (NSString * __nonnull)toFriendlyString:(NSDateFormatter * __null_unspecified)formatter;
@end


@interface NSDate (SWIFT_EXTENSION(SharelinkKernel))
- (NSString * __nonnull)toDateString;
- (NSString * __nonnull)toDateTimeString;
- (NSString * __nonnull)toAccurateDateTimeString;
- (NSString * __nonnull)toLocalDateString;
- (NSString * __nonnull)toLocalDateTimeString;
@end


@interface NSDate (SWIFT_EXTENSION(SharelinkKernel))
- (NSDate * __nonnull)addYears:(NSInteger)years;
- (NSDate * __nonnull)addMonthes:(NSInteger)monthes;
- (NSDate * __nonnull)addWeeks:(NSInteger)weeks;
- (NSDate * __nonnull)addDays:(NSInteger)days;
- (NSDate * __nonnull)addHours:(NSInteger)hours;
- (NSDate * __nonnull)addMinutes:(NSInteger)minutes;
- (NSDate * __nonnull)addSeconds:(NSTimeInterval)seconds;
@end


@interface NSDate (SWIFT_EXTENSION(SharelinkKernel))
@property (nonatomic, readonly) NSInteger totalSecondsSince1970;
@property (nonatomic, readonly) NSInteger totalMinutesSince1970;
@property (nonatomic, readonly) NSInteger totalHoursSince1970;
@property (nonatomic, readonly) NSInteger totalDaysSince1970;
@property (nonatomic, readonly) NSInteger totalSecondsSinceNow;
@property (nonatomic, readonly) NSInteger totalMinutesSinceNow;
@property (nonatomic, readonly) NSInteger totalHoursSinceNow;
@property (nonatomic, readonly) NSInteger totalDaysSinceNow;
@end

@class NSDateComponents;

@interface NSDate (SWIFT_EXTENSION(SharelinkKernel))
@property (nonatomic, readonly) NSInteger hourOfDate;
@property (nonatomic, readonly) NSInteger minuteOfDate;
@property (nonatomic, readonly) NSInteger secondOfDate;
@property (nonatomic, readonly) NSInteger yearOfDate;
@property (nonatomic, readonly) NSInteger monthOfDate;
@property (nonatomic, readonly) NSInteger dayOfDate;
@property (nonatomic, readonly) NSInteger weekDayOfDate;
@property (nonatomic, readonly, copy) NSString * __nonnull shortWeekdayOfDate;
@property (nonatomic, readonly, copy) NSString * __nonnull weekdayOfDate;
@property (nonatomic, readonly, strong) NSDateComponents * __nonnull currentTimeZoneComponents;
@end


SWIFT_CLASS("_TtC15SharelinkKernel34NewAliOSSFileAccessInfoListRequest")
@interface NewAliOSSFileAccessInfoListRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSArray<NSNumber *> * __null_unspecified fileSizes;
@end


SWIFT_CLASS("_TtC15SharelinkKernel30NewAliOSSFileAccessInfoRequest")
@interface NewAliOSSFileAccessInfoRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) NSInteger fileSize;
@end


SWIFT_CLASS("_TtC15SharelinkKernel21NewBahamutFireRequest")
@interface NewBahamutFireRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) NSInteger fileSize;
@end

@class NSBundle;

SWIFT_CLASS("_TtC15SharelinkKernel25NoStatusBarViewController")
@interface NoStatusBarViewController : UIViewController
- (BOOL)prefersStatusBarHidden;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel32NotifyNewMessagesReceivedRequest")
@interface NotifyNewMessagesReceivedRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNotification;

SWIFT_CLASS("_TtC15SharelinkKernel6Player")
@interface Player : UIViewController
@property (nonatomic, copy) NSString * __null_unspecified path;
@property (nonatomic, copy) NSString * __null_unspecified fillMode;
- (nonnull instancetype)init;
- (void)loadView;
- (void)viewDidDisappear:(BOOL)animated;
- (void)playFromBeginning;
- (void)playFromCurrentTime;
- (void)pause;
- (void)stop;
- (void)playerItemDidPlayToEndTime:(NSNotification * __nonnull)aNotification;
- (void)playerItemFailedToPlayToEndTime:(NSNotification * __nonnull)aNotification;
- (void)applicationWillResignActive:(NSNotification * __nonnull)aNotification;
- (void)applicationDidEnterBackground:(NSNotification * __nonnull)aNotification;
- (void)observeValueForKeyPath:(NSString * __nullable)keyPath ofObject:(id __nullable)object change:(NSDictionary<NSString *, id> * __nullable)change context:(void * __null_unspecified)context;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface Player (SWIFT_EXTENSION(SharelinkKernel))
- (void)reset;
@end

@class UIImage;
@class CIColor;
@class AVCaptureOutput;
@class AVCaptureConnection;

SWIFT_CLASS("_TtC15SharelinkKernel6QRCode")
@interface QRCode : NSObject <AVCaptureMetadataOutputObjectsDelegate>

/// the scan rect, default is the bounds of the scan view, can modify it if need
@property (nonatomic) CGRect scanFrame;

/// init function
///
/// \param autoRemoveSubLayers remove sub layers auto after detected code image, defalt is false
///
/// \param lineWidth line width, default is 4
///
/// \param strokeColor stroke color, default is Green
///
/// \param maxDetectedCount max detecte count, default is 20
///
/// \returns  the scanner object
- (nonnull instancetype)initWithAutoRemoveSubLayers:(BOOL)autoRemoveSubLayers lineWidth:(CGFloat)lineWidth strokeColor:(UIColor * __nonnull)strokeColor maxDetectedCount:(NSInteger)maxDetectedCount OBJC_DESIGNATED_INITIALIZER;

/// generate image
///
/// \param stringValue string value to encoe
///
/// \param avatarImage avatar image will display in the center of qrcode image
///
/// \param avatarScale the scale for avatar image, default is 0.25
///
/// \param color the CI color for forenground, default is black
///
/// \param backColor th CI color for background, default is white
///
/// \returns  the generated image
+ (UIImage * __nullable)generateImage:(NSString * __nonnull)stringValue avatarImage:(UIImage * __nullable)avatarImage avatarScale:(CGFloat)avatarScale color:(CIColor * __nonnull)color backColor:(CIColor * __nonnull)backColor;

/// prepare scan
///
/// \param view the scan view, the preview layer and the drawing layer will be insert into this view
///
/// \param completion the completion call back
- (void)prepareScan:(UIView * __nonnull)view completion:(void (^ __nonnull)(NSString * __nonnull))completion;

/// start scan
- (void)startScan;

/// stop scan
- (void)stopScan;
- (void)captureOutput:(AVCaptureOutput * __null_unspecified)captureOutput didOutputMetadataObjects:(NSArray * __null_unspecified)metadataObjects fromConnection:(AVCaptureConnection * __null_unspecified)connection;
- (void)removeAllLayers;
@end


SWIFT_CLASS("_TtC15SharelinkKernel14ReShareRequest")
@interface ReShareRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified pShareId;
@property (nonatomic, copy) NSString * __null_unspecified message;
@property (nonatomic, copy) NSArray<SharelinkTheme *> * __null_unspecified tags;
@end


SWIFT_CLASS("_TtC15SharelinkKernel29RegistNewSharelinkUserRequest")
@interface RegistNewSharelinkUserRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified region;
@property (nonatomic, copy) NSString * __null_unspecified nickName;
@property (nonatomic, copy) NSString * __null_unspecified motto;
@property (nonatomic, copy) NSString * __null_unspecified appkey;
@property (nonatomic, copy) NSString * __null_unspecified accountId;
@property (nonatomic, copy) NSString * __null_unspecified accessToken;
@end


SWIFT_CLASS("_TtC15SharelinkKernel17RemoveTagsRequest")
@interface RemoveTagsRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSArray<NSString *> * __null_unspecified tagIds;
@end


SWIFT_CLASS("_TtC15SharelinkKernel14SendFileResult")
@interface SendFileResult : BahamutObject
@property (nonatomic, copy) NSString * __null_unspecified message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel18SendMessageRequest")
@interface SendMessageRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (int32_t)getCurrentRequestCount;
- (int32_t)getMaxRequestCount;
- (void)incRequest;
- (void)decRequest;
@property (nonatomic, strong) NSDate * __null_unspecified time;
@property (nonatomic, copy) NSString * __null_unspecified chatId;
@property (nonatomic, copy) NSString * __nonnull type;
@property (nonatomic, copy) NSString * __null_unspecified message;
@property (nonatomic, strong) NSData * __null_unspecified messageData;
@property (nonatomic, copy) NSString * __null_unspecified audienceId;
@property (nonatomic, copy) NSString * __null_unspecified shareId;
@end


SWIFT_CLASS("_TtC15SharelinkKernel12SendTagModel")
@interface SendTagModel : BahamutObject
@property (nonatomic, copy) NSString * __null_unspecified name;
@property (nonatomic, copy) NSString * __null_unspecified type;
@property (nonatomic, copy) NSString * __null_unspecified data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel17ShareLinkFilmView")
@interface ShareLinkFilmView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setThumb:(UIImage * __nonnull)img;
- (void)clearThumb;
@property (nonatomic, copy) NSString * __null_unspecified filePath;
- (void)taskCompleted:(NSString * __nonnull)fileIdentifier result:(id __null_unspecified)result;
- (void)taskProgress:(NSString * __nonnull)fileIdentifier persent:(float)persent;
- (void)taskFailed:(NSString * __nonnull)fileIdentifier result:(id __null_unspecified)result;
- (void)layoutSubviews;
@property (nonatomic) BOOL autoPlay;
@property (nonatomic) BOOL autoLoad;
@property (nonatomic) BOOL canSwitchToFullScreen;
@property (nonatomic) BOOL showTimeLine;
@property (nonatomic) BOOL isMute;
@property (nonatomic) BOOL isPlaybackLoops;
- (void)playerBufferingStateDidChange:(Player * __nonnull)player;
- (void)playerPlaybackDidEnd:(Player * __nonnull)player;
- (void)playerPlaybackStateDidChange:(Player * __nonnull)player;
- (void)playerPlaybackWillStartFromBeginning:(Player * __nonnull)player;
- (void)playerReady:(Player * __nonnull)player;
@end



SWIFT_CLASS("_TtC15SharelinkKernel10ShareThing")
@interface ShareThing : BahamutObject
@property (nonatomic, copy) NSString * __null_unspecified shareId;
@property (nonatomic, copy) NSString * __null_unspecified pShareId;
@property (nonatomic, copy) NSString * __null_unspecified userId;
@property (nonatomic, copy) NSString * __null_unspecified userNick;
@property (nonatomic, copy) NSString * __null_unspecified avatarId;
@property (nonatomic, copy) NSString * __null_unspecified shareTime;
@property (nonatomic, copy) NSString * __null_unspecified shareType;
@property (nonatomic, copy) NSString * __null_unspecified message;
@property (nonatomic, copy) NSString * __null_unspecified shareContent;
@property (nonatomic, copy) NSArray<NSString *> * __null_unspecified voteUsers;
@property (nonatomic, copy) NSArray<NSString *> * __null_unspecified forTags;
@property (nonatomic, copy) NSString * __null_unspecified reshareable;
- (NSString * __nonnull)getObjectUniqueIdName;
@property (nonatomic, readonly, strong) NSDate * __null_unspecified shareTimeOfDate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ShareThing (SWIFT_EXTENSION(SharelinkKernel))
@end


@interface ShareThing (SWIFT_EXTENSION(SharelinkKernel))
- (BOOL)isUserShare;
- (BOOL)isMessageShare;
- (BOOL)isAddTagMessage;
- (BOOL)isFocusTagMessage;
- (BOOL)isTextMessage;
- (BOOL)canReshare;
@end


SWIFT_CLASS("_TtC15SharelinkKernel19ShareUpdatedMessage")
@interface ShareUpdatedMessage : BahamutObject
@property (nonatomic, copy) NSString * __null_unspecified shareId;
@property (nonatomic, copy) NSString * __null_unspecified time;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ShareUpdatedMessage (SWIFT_EXTENSION(SharelinkKernel))
@end

@class UIWindow;
@class UIApplication;
@class NSError;
@class NSURL;

SWIFT_CLASS("_TtC15SharelinkKernel20SharelinkAppDelegate")
@interface SharelinkAppDelegate : UIResponder <UIApplicationDelegate>
+ (void)startSharelink;
@property (nonatomic, strong) UIWindow * __nullable window;
- (BOOL)application:(UIApplication * __nonnull)application didFinishLaunchingWithOptions:(NSDictionary * __nullable)launchOptions;
- (void)application:(UIApplication * __nonnull)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData * __nonnull)deviceToken;
- (void)application:(UIApplication * __nonnull)application didReceiveRemoteNotification:(NSDictionary * __nonnull)userInfo;
- (void)application:(UIApplication * __nonnull)application didFailToRegisterForRemoteNotificationsWithError:(NSError * __nonnull)error;
- (BOOL)application:(UIApplication * __nonnull)app openURL:(NSURL * __nonnull)url options:(NSDictionary<NSString *, id> * __nonnull)options;
- (BOOL)application:(UIApplication * __nonnull)application openURL:(NSURL * __nonnull)url sourceApplication:(NSString * __nullable)sourceApplication annotation:(id __nonnull)annotation;
- (BOOL)application:(UIApplication * __nonnull)application handleOpenURL:(NSURL * __nonnull)url;
- (void)applicationWillResignActive:(UIApplication * __nonnull)application;
- (void)applicationDidEnterBackground:(UIApplication * __nonnull)application;
- (void)applicationWillEnterForeground:(UIApplication * __nonnull)application;
- (void)applicationDidBecomeActive:(UIApplication * __nonnull)application;
- (void)applicationWillTerminate:(UIApplication * __nonnull)application;
- (UIInterfaceOrientationMask)application:(UIApplication * __nonnull)application supportedInterfaceOrientationsForWindow:(UIWindow * __nullable)window;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel14SharelinkTheme")
@interface SharelinkTheme : BahamutObject
@property (nonatomic, copy) NSString * __null_unspecified tagId;
@property (nonatomic, copy) NSString * __null_unspecified tagName;
@property (nonatomic, copy) NSString * __null_unspecified tagColor;
@property (nonatomic, copy) NSString * __null_unspecified data;
@property (nonatomic, copy) NSString * __null_unspecified type;
@property (nonatomic, copy) NSString * __null_unspecified domain;
@property (nonatomic, copy) NSString * __null_unspecified isFocus;
@property (nonatomic, copy) NSString * __null_unspecified showToLinkers;
@property (nonatomic, copy) NSString * __null_unspecified time;
- (NSString * __nonnull)getThemeString;
- (NSString * __nonnull)getObjectUniqueIdName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface SharelinkTheme (SWIFT_EXTENSION(SharelinkKernel))
@end


@interface SharelinkTheme (SWIFT_EXTENSION(SharelinkKernel))
@end


@interface SharelinkTheme (SWIFT_EXTENSION(SharelinkKernel))
@end


@interface SharelinkTheme (SWIFT_EXTENSION(SharelinkKernel))
- (BOOL)isTypeOf:(NSString * __nonnull)type;
- (BOOL)isDomainOf:(NSString * __nonnull)domain;
- (BOOL)isSystemTheme;
- (BOOL)isCustomTheme;
- (BOOL)isResharelessTheme;
- (BOOL)isKeywordTheme;
- (BOOL)isGeoTheme;
- (BOOL)isSharelinkerTheme;
- (BOOL)isFeedbackTheme;
- (BOOL)isBroadcastTheme;
- (BOOL)isPrivateTheme;
@end


SWIFT_CLASS("_TtC15SharelinkKernel11Sharelinker")
@interface Sharelinker : BahamutObject
@property (nonatomic, copy) NSString * __null_unspecified userId;
@property (nonatomic, copy) NSString * __null_unspecified nickName;
@property (nonatomic, copy) NSString * __null_unspecified noteName;
@property (nonatomic, copy) NSString * __null_unspecified avatarId;
@property (nonatomic, copy) NSString * __null_unspecified personalVideoId;
@property (nonatomic, copy) NSString * __null_unspecified createTime;
@property (nonatomic, copy) NSString * __null_unspecified motto;
@property (nonatomic, strong) NSNumber * __null_unspecified level;
@property (nonatomic, strong) NSNumber * __null_unspecified levelScore;
- (NSString * __nonnull)getObjectUniqueIdName;
@property (nonatomic, readonly, strong) NSDate * __null_unspecified createTimeOfDate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface Sharelinker (SWIFT_EXTENSION(SharelinkKernel))
@end


SWIFT_CLASS("_TtC15SharelinkKernel17SharelinkerThemes")
@interface SharelinkerThemes : BahamutObject
@property (nonatomic, copy) NSString * __null_unspecified userId;
@property (nonatomic, copy) NSArray<SharelinkTheme *> * __null_unspecified tags;
- (NSString * __nonnull)getObjectUniqueIdName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIColor (SWIFT_EXTENSION(SharelinkKernel))
@end


@interface UIColor (SWIFT_EXTENSION(SharelinkKernel))

/// Creates a color from an hex string.
///
/// :param: hexString A hexa-decimal color string representation.
- (nonnull instancetype)initWithHexString:(NSString * __nonnull)hexString;

/// Creates a color from an hex integer.
///
/// :param: hex A hexa-decimal UInt32 that represents a color.
- (nonnull instancetype)initWithHex:(uint32_t)hex;

/// Returns the color representation as hexadecimal string.
///
/// :returns: A string similar to this pattern "#f4003b".
- (NSString * __nonnull)toHexString;

/// Returns the color representation as an integer.
///
/// :returns: A UInt32 that represents the hexa-decimal color.
- (uint32_t)toHex;

/// Returns the red component.
///
/// :returns: The red component as CGFloat.
- (CGFloat)redComponent;

/// Returns the green component.
///
/// :returns: The green component as CGFloat.
- (CGFloat)greenComponent;

/// Returns the blue component.
///
/// :returns: The blue component as CGFloat.
- (CGFloat)blueComponent;

/// Returns the alpha component.
///
/// :returns: The alpha component as CGFloat.
- (CGFloat)alphaComponent;

/// Initializes and returns a color object using the specified opacity and HSL component values.
///
/// :param: hue The hue component of the color object, specified as a value from 0.0 to 1.0 (0.0 for 0 degree and 1.0 for 360 degree).
/// :param: saturation The saturation component of the color object, specified as a value from 0.0 to 1.0.
/// :param: lightness The lightness component of the color object, specified as a value from 0.0 to 1.0.
/// :param: alpha The opacity value of the color object, specified as a value from 0.0 to 1.0.
- (nonnull instancetype)initWithHue:(CGFloat)hue saturation:(CGFloat)saturation lightness:(CGFloat)lightness alpha:(CGFloat)alpha;

/// Returns a boolean value that indicates whether the receiver is equal to the given hexa-decimal string.
///
/// :param: hexString A hexa-decimal color number representation to be compared to the receiver.
///
/// :returns: true if the receiver and the string are equals, otherwise false.
- (BOOL)isEqualToHexString:(NSString * __nonnull)hexString;

/// Returns a boolean value that indicates whether the receiver is equal to the given hexa-decimal integer.
///
/// :param: hex A UInt32 that represents the hexa-decimal color.
///
/// :returns: true if the receiver and the integer are equals, otherwise false.
- (BOOL)isEqualToHex:(uint32_t)hex;

/// Creates and returns a color object with the hue rotated along the color wheel by the given amount.
///
/// :param: amount A float representing the number of degrees as ratio (usually -1.0 for -360 degree and 1.0 for 360 degree).
///
/// :returns: A UIColor object with the hue changed.
- (UIColor * __nonnull)adjustedHueColor:(CGFloat)amount;

/// Creates and returns the complement of the color object.
///
/// This is identical to adjustedHueColor(0.5).
///
/// :returns: The complement UIColor.
///
/// :see: adjustedHueColor:
- (UIColor * __nonnull)complementColor;

/// Creates and returns a lighter color object.
///
/// :returns: An UIColor lightened with an amount of 0.2.
///
/// :see: lightenColor:
- (UIColor * __nonnull)lighterColor;

/// Creates and returns a color object with the lightness increased by the given amount.
///
/// :param: amount Float between 0.0 and 1.0.
///
/// :returns: A lighter UIColor.
- (UIColor * __nonnull)lightenColor:(CGFloat)amount;

/// Creates and returns a darker color object.
///
/// :returns: A UIColor darkened with an amount of 0.2.
///
/// :see: darkenColor:
- (UIColor * __nonnull)darkerColor;

/// Creates and returns a color object with the lightness decreased by the given amount.
///
/// :param: amount Float between 0.0 and 1.0.
///
/// :returns: A darker UIColor.
- (UIColor * __nonnull)darkenColor:(CGFloat)amount;

/// Creates and returns a color object with the saturation increased by the given amount.
///
/// :returns: A UIColor more saturated with an amount of 0.2.
///
/// :see: saturateColor:
- (UIColor * __nonnull)saturatedColor;

/// Creates and returns a color object with the saturation increased by the given amount.
///
/// :param: amount Float between 0.0 and 1.0.
///
/// :returns: A UIColor more saturated.
- (UIColor * __nonnull)saturateColor:(CGFloat)amount;

/// Creates and returns a color object with the saturation decreased by the given amount.
///
/// :returns: A UIColor less saturated with an amount of 0.2.
///
/// :see: desaturateColor:
- (UIColor * __nonnull)desaturatedColor;

/// Creates and returns a color object with the saturation decreased by the given amount.
///
/// :param: amount Float between 0.0 and 1.0.
///
/// :returns: A UIColor less saturated.
- (UIColor * __nonnull)desaturateColor:(CGFloat)amount;

/// Creates and returns a color object converted to grayscale.
///
/// This is identical to desaturateColor(1).
///
/// :returns: A grayscale UIColor.
///
/// :see: desaturateColor:
- (UIColor * __nonnull)grayscaledColor;

/// Creates and return a color object where the red, green, and blue values are inverted, while the opacity is left alone.
///
/// :returns: An inverse (negative) of the original color.
- (UIColor * __nonnull)invertColor;

/// Mixes the given color object with the receiver.
///
/// Specifically, takes the average of each of the RGB components, optionally weighted by the given percentage. The opacity of the colors object is also considered when weighting the components.
///
/// :param: color A color object to mix with the receiver.
/// :param: weight The weight specifies the amount of the given color object (between 0 and 1). The default value is 0.5, which means that half the given color and half the receiver color object should be used. 0.25 means that a quarter of the given color object and three quarters of the receiver color object should be used.
///
/// :returns: A color object corresponding to the two colors object mixed together.
- (UIColor * __nonnull)mixWithColor:(UIColor * __nonnull)color weight:(CGFloat)weight;

/// Creates and returns a color object corresponding to the mix of the receiver and an amount of white color, which increases lightness.
///
/// :param: amount Float between 0.0 and 1.0. The default amount is equal to 0.2.
///
/// :returns: A lighter UIColor.
- (UIColor * __nonnull)tintColor:(CGFloat)amount;

/// Creates and returns a color object corresponding to the mix of the receiver and an amount of black color, which reduces lightness.
///
/// :param: amount Float between 0.0 and 1.0. The default amount is equal to 0.2.
///
/// :returns: A darker UIColor.
- (UIColor * __nonnull)shadeColor:(CGFloat)amount;
@end


@interface UIImage (SWIFT_EXTENSION(SharelinkKernel))
@end


@interface UIImage (SWIFT_EXTENSION(SharelinkKernel))
@end


@interface UIImage (SWIFT_EXTENSION(SharelinkKernel))
@end


@interface UIView (SWIFT_EXTENSION(SharelinkKernel))
- (void)animationDidStop:(CAAnimation * __nonnull)anim finished:(BOOL)flag;
@end


@interface UIViewController (SWIFT_EXTENSION(SharelinkKernel))
@end


@interface UIViewController (SWIFT_EXTENSION(SharelinkKernel))
@end


@interface UIViewController (SWIFT_EXTENSION(SharelinkKernel))
@end


@interface UIViewController (SWIFT_EXTENSION(SharelinkKernel))
@end

@class UITouch;
@class UIEvent;

@interface UIViewController (SWIFT_EXTENSION(SharelinkKernel))
- (void)touchesBegan:(NSSet<UITouch *> * __nonnull)touches withEvent:(UIEvent * __nullable)event;
@end

@class MBProgressHUD;

@interface UIViewController (SWIFT_EXTENSION(SharelinkKernel)) <MBProgressHUDDelegate>
- (void)hudWasHidden:(MBProgressHUD * __null_unspecified)hud;
@end


SWIFT_CLASS("_TtC15SharelinkKernel29UpdateAccountBirthdateRequest")
@interface UpdateAccountBirthdateRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) NSDate * __null_unspecified birthdate;
@end


SWIFT_CLASS("_TtC15SharelinkKernel24UpdateAccountNameRequest")
@interface UpdateAccountNameRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified name;
@end


SWIFT_CLASS("_TtC15SharelinkKernel19UpdateAvatarRequest")
@interface UpdateAvatarRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified newAvatarId;
@end


SWIFT_CLASS("_TtC15SharelinkKernel31UpdateLinkedUserNoteNameRequest")
@interface UpdateLinkedUserNoteNameRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified newNoteName;
@property (nonatomic, copy) NSString * __null_unspecified userId;
@end


SWIFT_CLASS("_TtC15SharelinkKernel25UpdateProfileVideoRequest")
@interface UpdateProfileVideoRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified newProfileVideoId;
@end


SWIFT_CLASS("_TtC15SharelinkKernel36UpdateSharelinkerProfileMottoRequest")
@interface UpdateSharelinkerProfileMottoRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified motto;
@end


SWIFT_CLASS("_TtC15SharelinkKernel39UpdateSharelinkerProfileNickNameRequest")
@interface UpdateSharelinkerProfileNickNameRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified nickName;
@end


SWIFT_CLASS("_TtC15SharelinkKernel16UpdateTagRequest")
@interface UpdateTagRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified tagId;
@property (nonatomic, copy) NSString * __null_unspecified data;
@property (nonatomic, copy) NSString * __null_unspecified isFocus;
@property (nonatomic, copy) NSString * __null_unspecified tagName;
@property (nonatomic, copy) NSString * __null_unspecified tagColor;
@property (nonatomic, copy) NSString * __null_unspecified isShowToLinkers;
@property (nonatomic, copy) NSString * __null_unspecified type;
@end


SWIFT_CLASS("_TtC15SharelinkKernel36UpdateUserLinkStatusWithOtherRequest")
@interface UpdateUserLinkStatusWithOtherRequest : ShareLinkSDKRequestBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * __null_unspecified status;
@property (nonatomic, copy) NSString * __null_unspecified userId;
@end


SWIFT_CLASS("_TtC15SharelinkKernel8UserLink")
@interface UserLink : BahamutObject
@property (nonatomic, copy) NSString * __null_unspecified linkId;
@property (nonatomic, copy) NSString * __null_unspecified masterUserId;
@property (nonatomic, copy) NSString * __null_unspecified slaveUserId;
@property (nonatomic, copy) NSString * __null_unspecified status;
@property (nonatomic, copy) NSString * __null_unspecified createTime;
- (NSString * __nonnull)getObjectUniqueIdName;
@property (nonatomic, readonly, strong) NSDate * __null_unspecified createTimeOfDate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15SharelinkKernel4Vote")
@interface Vote : BahamutObject
@property (nonatomic, copy) NSString * __null_unspecified voteId;
@property (nonatomic, copy) NSString * __null_unspecified shareId;
- (NSString * __nonnull)getObjectUniqueIdName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


#pragma clang diagnostic pop
